#!/usr/bin/env ruby

# Takes comments.yml generated by wordpressxml2jekyll.rb and posts them to your Disqus forum.
# sudo gem install disqus

require 'disqus'
require 'disqus/api'

COMMENTS_YAML_FILE = '/tmp/export/comments.yml'

Disqus::defaults[:api_key] = "N4wWciM45UAfBJe6QbylR0mfQ340WH7kdEKlBi7q5Tb0QeAKHOxP7wC6W5WyJWWz"

forum_id = Disqus::Api.get_forum_list["message"].first["id"]
fak = Disqus::Api.get_forum_api_key(:forum_id => forum_id)["message"]

File.open(COMMENTS_YAML_FILE) do |yf|
  YAML.each_document( yf ) do |c|
    thread = Disqus::Api.get_thread_by_url(:forum_api_key => fak, :url => c.ivars["post_url"])
    Disqus::Api.create_post(:forum_api_key => fak,
                            :thread_id => thread["message"]["id"],
                            :message => c.ivars["content"],
                            :author_name => c.ivars["author_name"],
                            :author_email => c.ivars["author_email"],
                            :author_url => c.ivars["author_url"],
                            :created_at => Time.parse(c.ivars["created_at"].to_s).strftime("%Y-%m-%dT%H:%M"))
  end
end